export const fruits = [
  { value: 'Apple' },
  { value: 'Banana' },
  { value: 'Grape' },
  { value: 'Orange' },
  { value: 'Pear' },
  { value: 'Pineapple' },
];

export const artists = [
  { value: 'Crystal Lake' },
  { value: 'Eric Clapton' },
  { value: 'James Blake' },
  { value: 'John Frusciante' },
  { value: 'John Mayer' },
  { value: 'Justin Vernon' },
  { value: 'Parkway Drive' },
];

export const states = [
  { abbreviation: 'AL', value: 'Alabama' },
  { abbreviation: 'AK', value: 'Alaska' },
  { abbreviation: 'AS', value: 'American Samoa' },
  { abbreviation: 'AZ', value: 'Arizona' },
  { abbreviation: 'AR', value: 'Arkansas' },
  { abbreviation: 'CA', value: 'California' },
  { abbreviation: 'CO', value: 'Colorado' },
  { abbreviation: 'CT', value: 'Connecticut' },
  { abbreviation: 'DE', value: 'Delaware' },
  { abbreviation: 'DC', value: 'District Of Columbia' },
  { abbreviation: 'FM', value: 'Federated States Of Micronesia' },
  { abbreviation: 'FL', value: 'Florida' },
  { abbreviation: 'GA', value: 'Georgia' },
  { abbreviation: 'GU', value: 'Guam' },
  { abbreviation: 'HI', value: 'Hawaii' },
  { abbreviation: 'ID', value: 'Idaho' },
  { abbreviation: 'IL', value: 'Illinois' },
  { abbreviation: 'IN', value: 'Indiana' },
  { abbreviation: 'IA', value: 'Iowa' },
  { abbreviation: 'KS', value: 'Kansas' },
  { abbreviation: 'KY', value: 'Kentucky' },
  { abbreviation: 'LA', value: 'Louisiana' },
  { abbreviation: 'ME', value: 'Maine' },
  { abbreviation: 'MH', value: 'Marshall Islands' },
  { abbreviation: 'MD', value: 'Maryland' },
  { abbreviation: 'MA', value: 'Massachusetts' },
  { abbreviation: 'MI', value: 'Michigan' },
  { abbreviation: 'MN', value: 'Minnesota' },
  { abbreviation: 'MS', value: 'Mississippi' },
  { abbreviation: 'MO', value: 'Missouri' },
  { abbreviation: 'MT', value: 'Montana' },
  { abbreviation: 'NE', value: 'Nebraska' },
  { abbreviation: 'NV', value: 'Nevada' },
  { abbreviation: 'NH', value: 'New Hampshire' },
  { abbreviation: 'NJ', value: 'New Jersey' },
  { abbreviation: 'NM', value: 'New Mexico' },
  { abbreviation: 'NY', value: 'New York' },
  { abbreviation: 'NC', value: 'North Carolina' },
  { abbreviation: 'ND', value: 'North Dakota' },
  { abbreviation: 'MP', value: 'Northern Mariana Islands' },
  { abbreviation: 'OH', value: 'Ohio' },
  { abbreviation: 'OK', value: 'Oklahoma' },
  { abbreviation: 'OR', value: 'Oregon' },
  { abbreviation: 'PW', value: 'Palau' },
  { abbreviation: 'PA', value: 'Pennsylvania' },
  { abbreviation: 'PR', value: 'Puerto Rico' },
  { abbreviation: 'RI', value: 'Rhode Island' },
  { abbreviation: 'SC', value: 'South Carolina' },
  { abbreviation: 'SD', value: 'South Dakota' },
  { abbreviation: 'TN', value: 'Tennessee' },
  { abbreviation: 'TX', value: 'Texas' },
  { abbreviation: 'UT', value: 'Utah' },
  { abbreviation: 'VT', value: 'Vermont' },
  { abbreviation: 'VI', value: 'Virgin Islands' },
  { abbreviation: 'VA', value: 'Virginia' },
  { abbreviation: 'WA', value: 'Washington' },
  { abbreviation: 'WV', value: 'West Virginia' },
  { abbreviation: 'WI', value: 'Wisconsin' },
  { abbreviation: 'WY', value: 'Wyoming' },
];
